--updated_updated_at_column
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;

--assign_patient_queue_no
BEGIN
  -- This makes the database find the next number automatically
  -- LOWER() ensures it works regardless of how you type 'walk-in'
  IF LOWER(NEW.patient_type) = 'walk-in' AND NEW.queue_no IS NULL THEN
    NEW.queue_no := (SELECT COALESCE(MAX(queue_no), 0) + 1 FROM public.patients);
  END IF;
  
  RETURN NEW;
END;



--DOCTORS TABLE
create table public.doctors (
  id serial not null,
  name character varying(255) not null,
  specializations jsonb null default '[]'::jsonb,
  is_active boolean null default true,
  created_at timestamp with time zone null default now(),
  constraint doctors_pkey primary key (id)
) TABLESPACE pg_default;

--CLINIC STAFF TABLE
create table public.clinic_staff (
  id uuid not null default gen_random_uuid (),
  email character varying(255) not null,
  staff_role character varying(50) not null,
  staff_id character varying(100) null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  full_name character varying(255) null,
  company_name character varying(255) null,
  phone_number character varying(20) null,
  constraint clinic_staff_pkey primary key (id),
  constraint clinic_staff_email_key unique (email),
  constraint clinic_staff_staff_id_key unique (staff_id),
  constraint clinic_staff_staff_role_check check (
    (
      (staff_role)::text = any (
        (
          array[
            'secretary'::character varying,
            'doctor'::character varying,
            'admin'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_staff_email on public.clinic_staff using btree (email) TABLESPACE pg_default;

create index IF not exists idx_staff_role on public.clinic_staff using btree (staff_role) TABLESPACE pg_default;

create index IF not exists idx_staff_phone on public.clinic_staff using btree (phone_number) TABLESPACE pg_default;

create trigger update_clinic_staff_updated_at BEFORE
update on clinic_staff for EACH row
execute FUNCTION update_updated_at_column ();

--PATIENT_PROFILES TABLE
create table public.patient_profiles (
  id uuid not null,
  full_name text not null,
  email text not null,
  phone_num text null,
  created_at timestamp with time zone null default now(),
  constraint patient_profiles_pkey primary key (id),
  constraint patient_profiles_email_key unique (email),
  constraint patient_profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

--PATIENTS TABLE
create table public.patients (
  id uuid not null default gen_random_uuid (),
  name character varying(255) null,
  age integer not null,
  phone_num character varying(20) not null,
  physician character varying(255) null,
  symptoms jsonb null default '[]'::jsonb,
  services jsonb null default '[]'::jsonb,
  days_since_onset integer null,
  patient_type character varying(20) null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  status text null default 'waiting'::text,
  appointment_datetime timestamp with time zone null,
  appointment_status text null,
  is_priority boolean null default false,
  priority_type text null,
  profile_id uuid null,
  queue_no integer generated by default as identity not null,
  in_queue boolean null default true,
  called_at timestamp with time zone null,
  queue_exit_time timestamp with time zone null,
  completed_at timestamp with time zone null,
  cancelled_at timestamp with time zone null,
  registered_at timestamp with time zone null default now(),
  assigned_doctor_id integer null,
  assigned_doctor_name character varying(255) null,
  is_returning_patient boolean null default false,
  requeued boolean null default false,
  original_queue_no integer null,
  is_inactive boolean null default false,
  rejection_reason text null,
  rejected_at timestamp with time zone null,
  patient_email character varying(255) null,
  constraint patients_pkey primary key (id),
  constraint unique_queue_no unique (queue_no),
  constraint patients_profile_id_fkey foreign KEY (profile_id) references patient_profiles (id) on delete set null,
  constraint patients_patient_type_check check (
    (
      (patient_type)::text = any (
        (
          array[
            'walk-in'::character varying,
            'appointment'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_patients_phone on public.patients using btree (phone_num) TABLESPACE pg_default;

create index IF not exists idx_patients_name on public.patients using btree (name) TABLESPACE pg_default;

create index IF not exists idx_patients_type on public.patients using btree (patient_type) TABLESPACE pg_default;

create index IF not exists idx_patients_queue_no on public.patients using btree (queue_no) TABLESPACE pg_default;

create index IF not exists idx_patients_status on public.patients using btree (status) TABLESPACE pg_default;

create index IF not exists idx_patients_in_queue on public.patients using btree (in_queue) TABLESPACE pg_default;

create index IF not exists idx_patients_email on public.patients using btree (patient_email) TABLESPACE pg_default;

create trigger update_patients_updated_at BEFORE
update on patients for EACH row
execute FUNCTION update_updated_at_column ();

create trigger tr_assign_queue_no BEFORE INSERT on patients for EACH row
execute FUNCTION assign_patient_queue_no ();

--APPOINTMENTS TABLE
create table public.appointments (
  id uuid not null default gen_random_uuid (),
  patient_id uuid null,
  appointment_datetime timestamp with time zone not null,
  status character varying(20) null default 'scheduled'::character varying,
  notes text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  queue_no integer null,
  constraint appointments_pkey primary key (id),
  constraint appointments_patient_id_fkey foreign KEY (patient_id) references patients (id) on delete CASCADE,
  constraint appointments_status_check check (
    (
      (status)::text = any (
        (
          array[
            'scheduled'::character varying,
            'completed'::character varying,
            'cancelled'::character varying,
            'no-show'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_appointments_datetime on public.appointments using btree (appointment_datetime) TABLESPACE pg_default;

create index IF not exists idx_appointments_patient_id on public.appointments using btree (patient_id) TABLESPACE pg_default;

create index IF not exists idx_appointments_status on public.appointments using btree (status) TABLESPACE pg_default;

create trigger update_appointments_updated_at BEFORE
update on appointments for EACH row
execute FUNCTION update_updated_at_column ();

--PATIENT_PROFILES TABLE
create table public.patient_profiles (
  id uuid not null,
  full_name text not null,
  email text not null,
  phone_num text null,
  created_at timestamp with time zone null default now(),
  constraint patient_profiles_pkey primary key (id),
  constraint patient_profiles_email_key unique (email),
  constraint patient_profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

-- SECTION 4: SECURITY & POLICIES

-- Enable RLS for core tables
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinic_staff ENABLE ROW LEVEL SECURITY;

-- Basic Policy: Allow authenticated staff to see everything
CREATE POLICY "Staff has full access" 
ON public.patients 
FOR ALL 
TO authenticated 
USING (
  EXISTS (SELECT 1 FROM public.clinic_staff WHERE email = auth.jwt() ->> 'email')
);